version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always
  
  app:
    build:
      context: .
    command: sh -c "python3 main.py"
    depends_on:
      - selenium